#!/usr/bin/env bash
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root_dir"

if [[ ! -d "vader.vim" ]]; then
  git clone --depth 1 https://github.com/junegunn/vader.vim.git vader.vim
fi

vim -Es -Nu test/vimrc -c 'Vader! test/*.vader' -c 'qa!'
